### PR TITLE
initial typescript types file

### PR DESCRIPTION
**Pull request by RWOverdijk**
I have this file in my `typings/` dir locally now and so far it works. ~I took everything from defaultProps to be optional and extended TextProps because... Well, it does.~

I made everything optional because upon inspecting the code, everything is.

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
Great, please also consider adding this file to `package.json`. by that typescript engine and IDEs can detect the type definition.

**package.json**

{
   ... // the other json tags
    `"types": PATH_TO_TYPE_DEFINITION_FILE`
}

**Comment by SaeedZhiany** [comment]
Great, please also consider adding this file to `package.json`. by that typescript engine and IDEs can detect the type definition.

**package.json**
```
{
   ... // the other json tags
    `"types": PATH_TO_TYPE_DEFINITION_FILE`
}
```

**Comment by RWOverdijk** [comment]
@SaeedZhiany I wasn't going to yet, but sure 😄

**Comment by deanhet** [comment]
This is great work and an excellent first contribution!
Closes #53. I've pulled it down and I'm happy with it. I'm assuming @SaeedZhiany is signing off on it too. 

Will merge and push out a release now. 👍🏻

**Pull request merged**
