### PR TITLE
Add scrolling speed and rename to bounceSpeed

### PR DESCRIPTION
**Pull request by RWOverdijk**
The current scrollingSpeed is confusingly the bounce speed. And the actual scrolling speed is a fixed value of 150.

I renamed the scrollingSpeed to bounceSpeed, and moved the fixed 150 value to a new prop called scrollingSpeed.

I do realise that this is a BC break, but I think it's for the better. If both my PRs end up getting merged I'll update the types of the other PR to include the new prop in this PR as well.

### CODE REVIEW

**Comment by deanhet** [comment]
This change makes sense but I'm keen to avoid breaking changes, especially since we're still using the same variable name for a different purpose. We could also perhaps change the `scrollingSpeed` name entirely so there's no confusion between old versions and new versions.
It doesn't quite feel like a big enough change to warrant a major version bump.

What are your thoughts on this transition?
- New code that keeps both the `bounceSpeed` and `scrollingSpeed` props pointing to the bounce speed (so it doesn't break existing functionality). Users can use either oft hem but there will be a `console.warn` for anyone still using  the `scrollingSpeed` prop, telling them to move over to the bounceSpeed prop as `scrollingSpeed` will be deprecated.
- After a period of time we push out another release, removing the scrollingSpeed prop entirely. People now have to use bounceSpeed if they want the same functionality as they had. Replace `console.warn` with a `console.error`
- We introduce a new prop for scrollingSpeed but called something different to avoid confusion with previous versions.

**Comment by RWOverdijk** [comment]
My thought is this change haha.

Semver dictates a major version bump. It's not a huge deal to have a major version bump as long as you have a changelog. If you want it deprecated first that's of course fine, too, but I recommend not doing that _because_ it's such a small change. It makes it easy to update for people using it.

**Comment by deanhet** [comment]
Fair enough, you're the one that done the work on it. 🙂 Happy to merge this and major bump the version as long as `scrollingSpeed` name isn't reused.
Some quick ideas, `marqueeSpeed`, `rotationSpeed`, `animationSpeed`

**Comment by RWOverdijk** [comment]
I don't like those suggestions. Using marqueeSpeed is too non-specific, same goes for rotation and animation. Which animation? Which marquee? Which rotation?

But this argument goes both ways and made me realise that I chose the wrong name to begin with. I'll rename it to `scrollSpeed` That way it's consistent. Bounce has a bounceSpeed, and scroll has a scrollSpeed.

All done.

**Pull request merged**
