### PR TITLE
fix RTL I18nManager

### PR DESCRIPTION
**Pull request by sm-hejazi**
Added I18nManager and check I18nManager.isRTL in two line

### CODE REVIEW

**Comment by deanhet** [comment]
Thanks for the PR! I've pulled down the branch and think I may have spotted an issue. It may just be my implementation though so before I correct something that might just be me, can you provide a quick piece of code to show how you would typically use RTL in this? 
I just want to make sure it has the exact same functionality as LTR.

**Comment by sm-hejazi** [comment]
`toValue: I18nManager.isRTL ? this.distance + 10 : -this.distance - 10,`

**Comment by deanhet** [comment]
Sorry, I meant when the code where you would actually use this. As in importing `TextTicker` and setting RTL.

**Comment by sm-hejazi** [comment]
I think my commit is complete, there is everything in it. You can find out how I use RTL with this library.
Please see my code and inform me if there is a problem:

[There is explanation in this page](https://github.com/deanhet/react-native-text-ticker/issues/18
)

**Comment by SaeedZhiany** [comment]
@sm-hejazi 
have you tested your code? @deanhet wants a simple runnable project to see your changes. can you provide the project on Github and share its URL?

**Comment by sm-hejazi** [comment]
@SaeedZhiany  yes! on Android&IOS in RTL is correct

**Comment by SaeedZhiany** [comment]
@sm-hejazi So what is the barrier for sharing your tested codes with us?

**Comment by sm-hejazi** [comment]
I understand you now :-D
ok, I create new example project & share with you.

**Comment by sm-hejazi** [comment]
For you:
[RTL_Test](https://github.com/sm-hejazi/rnTextTickerRtl)

**Comment by deanhet** [comment]
Thanks for taking the time to do this, it helps a lot.
I've pulled down your code and I've run through it. What you've provided seems to work for your use-case but there are a couple of issues I have spotted:

- When I remove the `animationType` prop, the RTL text scrolls the wrong way again. TextTicker should work both directions with just the default/no props.
- TextTicker has the ability to show the start of the string again as it's finishing (see the first scrolling line on screenshot example in readme). Line 290 of your PR seems to disable that if the user is using RTL. LTR and RTL should have the same feature set.

I'd be happy to take another look if you could address these issues.

**Pull request closed without merging**
